### ISSUE TITLE
Does it work for Influx (and others)? Should the name then be changed?

### ISSUE THREAD

**Issue by PallHaraldsson** [Ochibobo/QuestDBClient.jl#4]
Since it works for the "InfluxDB Line Protocol". I looked at Influx and QuestDB at the time, but not in too much detail. It it just that the latter is your focus?

Should there be some generic name that fits both, or should it then be Influx?

Even with no change, should Influx DB use be clarified in the docs?

**Comment by Ochibobo** [comment]
Hello..

QuestDB uses the Influx Line Protocol as one of the ways to insert data. 

I do like your suggestion though. I haven't tried it on Influx DB yet as I spent more time focusing primarily on studying QuestDB. Let me look into Influx DB and it's docs and possibly try out the package there.

Thanks for the suggestion @PallHaraldsson .

**Comment by Ochibobo** [comment]
I have checked InfluxDB's Docs. The implementation is different. The InfluxDB Line Protocol refers to the the text-based format for writing records (points) to the database. Their DB interface is exposed via a REST API. In QuestDB, a REST API is one of the ways the DB Interface is exposed. For writes, using ILP in QuestDB, one writes to a TCP socket directly while in InfluxDB, it's a POST request over HTTP.
